version: "3.8"

services:
  database:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: library
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  telegram_bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram_bot
    environment:
      TOKEN: 7960682573:AAG0RIa7XhWIkooi9TPzrYwAwT-M8WjUVDQ
      SQLALCHEMY_URL: postgresql+asyncpg://postgres:admin@database:5432/library
    depends_on:
      - database
    ports:
      - "8000:8000" # Порт для приложения (если нужно)
    volumes:
      - ./app:/app

  test:
  build:
    context: .
    dockerfile: Dockerfile
  environment:
    - SQLALCHEMY_URL=postgresql+asyncpg://postgres:admin@database:5432/library
  depends_on:
    - database
  command: pytest --cov=app --cov-report=xml

