version: "3.8"

services:
  # Уже существующие сервисы: database, telegram_bot
  database:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: library
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  telegram_bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram_bot
    environment:
      - TOKEN=7960682573:AAG0RIa7XhWIkooi9TPzrYwAwT-M8WjUVDQ
      - SQLALCHEMY_URL=postgresql+asyncpg://postgres:admin@database:5432/library
    depends_on:
      - database
    volumes:
      - ./app:/app

  test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram_bot_tests
    environment:
      - TOKEN=7960682573:AAG0RIa7XhWIkooi9TPzrYwAwT-M8WjUVDQ
      - SQLALCHEMY_URL=postgresql+asyncpg://postgres:admin@database:5432/library
    depends_on:
      - database
    volumes:
      - ./app:/app
    command: ["pytest", "app/test_handlers.py", "--junitxml=test-results.xml"]
    # Запуск тестов с выводом результатов в формате JUnit, чтобы можно было обработать в TeamCity

volumes:
  db_data:
